services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=senha123
      - POSTGRES_DB=roadmap4it
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - roadmap_network

networks:
  roadmap_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
